### ISSUE TITLE
Interpreting results

### ISSUE THREAD

**Issue by epi052** [serega/gaoya#18]
Good morning! 

I'm [exploring simhash as an alternative algorithm](https://github.com/epi052/feroxbuster/issues/711) to ssdeep for identifying near-duplicate webpage responses for [my project](https://github.com/epi052/feroxbuster). The reason is that ssdeep doesn't do well if the webpage's content length is below a certain threshold.

I currently use [fuzzyhash](https://docs.rs/fuzzyhash/latest/fuzzyhash/) and can ask it to compare two hashes, returning a similarity percentage:

```
s1: 24:hY6svD+6zSU6pedQf3Zvcn1BZdAe1nCr1LTHI5z8xTxS8f:3qD+2+pUAew85zsTUA 
s2: 24:hY6svD+6zSU6pedQf3Zvcn1BZdAe1nCr1LTHI5z8xnZS8f:3qD+2+pUAew85zsnsA

similarity: 97%
```

Is there a way for me to (correctly) interpret simhash's hamming distance as a percentage-based similarity? 

I played around with the 128bit simhash and it seems as though the maximum distance is 61? Could i use that as the maximum in calculating a percentage?

Side question: what is the relevance of the keys in this constructor?
```SimSipHasher128::new(1, 2)```

example webpage response below that differs slightly. ssdeep reports 97% similarity for the two static strings.

```rust
use gaoya::simhash::SimHash;
use gaoya::simhash::SimHashBits;
use gaoya::simhash::SimSipHasher128;

static goog32: &str = r#"<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/f1ae349ad8674a4c8e6ecc6403ffa2a2</code> was not found on this server.  <ins>That’s all we know.</ins>
"#;

static goog96: &str = r#"<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/some-longer/document/perhaps</code> was not found on this server.  <ins>That’s all we know.</ins>
"#;
fn main() {
    let sim_hash: SimHash<SimSipHasher128, u128, 128> = SimHash::new(SimSipHasher128::new(1, 2));
    let g1 = sim_hash.create_signature(whitespace_split(goog32));
    let g2 = sim_hash.create_signature(whitespace_split(goog96));
    println!("g1 {} g2  {} distance {}", g1, g2, g1.hamming_distance(&g2));
    println!("g1 {} g2  {} distance {}", g1, g2, g1.hamming_angle(&g2));
}
```

**Comment by serega** [comment]
Hello.
SimHash approximates cosine [`similarity`](https://deepai.org/machine-learning-glossary-and-terms/cosine-similarity). The function `hamming_angle` returns a crude approximation of the angle between two _unknown_ vectors in some unknown multidimensional vector space.  We can calculate the cosine similarity by taking the cosine of the angle
```rust
println!("g1 {} g2  {} cosine similarity {}", g1, g2, g1.hamming_angle(&g2).cos());
```

```text
g1 142505631118904753166100527226968672652 g2  142339477619431638681987410606945274252 distance 2
g1 142505631118904753166100527226968672652 g2  142339477619431638681987410606945274252 distance 0.04908738521234052
g1 142505631118904753166100527226968672652 g2  142339477619431638681987410606945274252 cosine similarity 0.9987954562051724
```
Cosine similarity is normally between `0 and 1`.  In theory can be negative, but probably rarely in practice.  Cosine function is non linear, so  multiplying by 100 does not give percentages of similarity, although results in the range `0...100`.
In practice, simhash is great for [finding near duplicates](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/33026.pdf), but  not so much for measuring similarity. 

Personally, I get better results with MinHash (for short text messages). MinHash approximates jaccard (set based) similarity
```rust
let min_hash = MinHasher16::new(256);
let g1 = min_hash.create_signature(whitespace_split(goog96));
let g2 = min_hash.create_signature(whitespace_split(goog32));
println!("minhash similarity {}", min_hash.compute_similarity(g1.iter(), g2.iter()));
println!("true jaccard similarity {}", compute_jaccard_similarity(whitespace_split(goog32), whitespace_split(goog96)));
```

```text
minhash similarity 0.95703125
true jaccard similarity 0.96031743
```

MinHash similarity returns value from `0..1`, and it can be [interpreted](https://www.statisticshowto.com/jaccard-index/) as percentages.

MinHash uses much bigger  hashes (signatures) resulting in large memory usage. For large number of documents you may want to use an[ index](https://docs.rs/gaoya/latest/gaoya/minhash/struct.MinHashIndex.html). 

You can also try different tokenization techniques. Using n-grams or  [shingles](https://docs.rs/gaoya/latest/gaoya/text/fn.shingle_text.html) is very common with both SimHash and MInHash.

**Comment by epi052** [comment]
thanks for the awesome reply! 

I was able to get a minhash implementation working, but would still like to test simhash against some edge cases i have.

In your linked paper, it looks like instead of a percentage based comparison, I could use simhash and check that the hamming distance is <= 3 in order to determine a near-duplicate. 

All I'm interested in is detection, so if the comparison would need to change to the hamming distance, that would be fine.

Did I misunderstand the values used in the paper?

For context, in my use-case, there would be a handful (<10 on average) of baseline (pre-computed at startup) hashes against which all subsequent pages (10s to 100s of thousands) would be compared (computed during runtime in their own thread).

**Comment by serega** [comment]
If you only need near duplicates then you could just use simhash and hamming distance. In the paper they used 64bit hashes, so for 128bit hashes the threshold should be about 6.  Bigger hashes reduce false positives. In the paper they indexed 8B webpages using 64bit hashes, which is a lot. Unless you go above that you can just use 64bit.

```rust
let sim_hash: SimHash<SimSipHasher64, u64, 64> = SimHash::new(SimSipHasher64::new(1, 2));
```
The last two arguments are just initialization keys to SipHasher, which can be anything as long as they are the same. 

Small number (up to hundreds and may be even thousands)  hashes can be compared directly. `hamming_distance` should compile to just a single instruction `popcnt`. For millions of documents [index](https://docs.rs/gaoya/latest/gaoya/simhash/struct.SimHashIndex.html) will be much faster. 

I've never used LSH on web pages. The paper mentions preprocessing steps with tokenization, case folding, stop-word removal. I am sure it helps, but I only have very basic tokenization functions. There probably crates that can parse html and spit out token stream.

**Comment by epi052** [comment]
Thank you again! 

I've already swapped things to simhash using 64bit hashes, so glad to hear I'm on the right track :grin: 

I actually have some nlp related functions laying around in the project I can reuse for the pre-processing. 

Thanks again for all your patience and help!
