### ISSUE TITLE
Character analyzer

### ISSUE THREAD

**Issue by ZJaume** [serega/gaoya#21]
It would be nice to have character analyzer to be able to process languages without spaces, like Chinese. Seeing https://github.com/serega/gaoya/blob/master/gaoya/src/text/tokenizers.rs it seems that is doable with the shingles? But this option is not available through the Python interface, is it?

**Comment by serega** [comment]
Character analyzer is [exposed](https://github.com/serega/gaoya/blob/master/py-gaoya/gaoya/minhash.py#L38) in the python interface.
`analyzer='char'`
You can also provide a callable with your tokenization logic, but if performance matters the Rust tokenizer will likely be faster.

**Comment by ZJaume** [comment]
Oh, that's right. Thanks!
